version: '3.8'
services:

  # REACT CONTAINER
  react:
    container_name: react
    build:
      context: ./client
      dockerfile: react.Dockerfile
    volumes:
      - ./client:/usr/src/client
      - /client/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - node

  # NODE EXPRESS CONTAINER
  node: 
    container_name: express
    # bind mount 
    # <localDir>:<workDirInContainer> 
    # :ro = read-only
    volumes:
      - ./:/usr/src/backend:ro
    restart: always
    # "build" creates a custom image
    # . param = searches for Dockerfile in root dir
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    depends_on:
      - mongo

  # MONGO CONTAINER
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      # <nameOfVolume>:<directoryInContainer>
      - mongoDB:/data/db

volumes:
  # Making the volume accessible by other containers
  mongoDB: